name: test

on:
  workflow_dispatch: 
    
permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: test upload-to-oss
              uses: ./
              with:
                source: 'src/index.ts'
                dest: 'test/index.ts'
                bucket: ${{secrets.bucket}}
                region: ${{secrets.region}}
                accessKeyId: ${{secrets.accessKeyId}}
                accessKeySecret: ${{secrets.accessKeySecret}}

            - name: zip
              run: cd src && zip -r ~/docker-compose.zip .

            - name: upload
              uses: hexf00/upload-to-oss@v1
              with:
                source: '~/docker-compose.zip'
                dest: 'test/test.zip'
                bucket: ${{secrets.bucket}}
                region: ${{secrets.region}}
                accessKeyId: ${{secrets.accessKeyId}}
                accessKeySecret: ${{secrets.accessKeySecret}}
